name: Android Release CI

on:
  workflow_dispatch:

env:
  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
  LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
  PLAY_SERVICE_JSON: ${{ secrets.PLAY_SERVICE_JSON }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set config files
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -d > app/google-services.json
          echo $LOCAL_PROPERTIES | base64 -d > local.properties

      - name: Run Build
        run: ./gradlew bundleRelease

      - name: Set publisher files
        run: echo $PLAY_SERVICE_JSON | base64 -d > google-play-service.json

      - name: Run Release
        run: ./gradlew publishBundle

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
          username: GHA_RELEASE
          icon_emoji: ':sunglasses:'
          channel: '#android-app'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
